### ISSUE TITLE
Sample dashboards

### ISSUE THREAD

**Issue by QCU87Z** [remijouannet/graftorio2#11]
Hi,

I was wondering if you have any example for queries for creating dashboards. I have the data going into Grafana but cant work out how to graph how many sciences packs I am making per minute etc.

I know its not really about your mod and more about my ability to use grafana and prometheus but some examples would be awesome to help people along.

Great mod cheers.

**Comment by Kariton** [comment]
Hey,

I have a few _mostly_ polished dashboards with datalinks etc.
They include the following:
- \# Info
- \# Items
- 1.1 - Default: Electricity
- 1.2 - Default: Items
- 1.3 - Default: Fluids
- 1.4 - Default: Buildings
- 1.5 - Default: Pollution
- 1.6 - Default: Kills
- 1.7 - Default: Logistics
- 3.1 - Rate: Electricity
- 3.2 - Rate: Items
- 3.2.1 - Rate: Storage
- 3.2.2 - Rate: Science Packs
- 3.3 - Rate: Fluids
- 3.4 - Rate: Buildings
- 4.5 - Rate: Train
- 4.1 - Misc: Items
- 4.2 - Misc: Buildings
- 4.3 - Misc: Kills
- 4.4 - Misc: Logistic Network
- 4.4.1 - Misc: Logistic Items
- 4.4.2 - Misc: Robots
- 4.5 - Misc: Train

### `Info` - overall stats
  - UPS
  - Game Time (Play Time)
  - Total Players (unique players)
  - Current online players
  - Map Seed [no data]
  - Installed mods [no data]
  - Evolution [no data]
  - Evolution Composition [no data]
  - Current research progress [no data]
  - research queue [no data]
  - total rockets launched
  - rockets per `TimeScale` based on last hour

### `Items` - important items - delta production / consumption
  - Science per `TimeScale` [datalink: `3.2.2 - Rate: Science Packs`]
  - Circuits per `TimeScale` [datalink: `4.1 - Misc: Items`]
  - Materials per `TimeScale` (Iron, Copper, Plastic, Steel) [datalink: `4.1 - Misc: Items`]
  - Components per `TimeScale` (Battery, FRF, LDS, RCU, Rocket Fuel) [datalink: `4.1 - Misc: Items`]

### `Default` - rebuild of ingame graphs (as close as possible)
  - 1.1 - Default: Electricity [datalink: `3.1 - Rate: Electricity`]
  - 1.2 - Default: Items  [datalink: `3.2 - Rate: Items`]
  - 1.3 - Default: Fluids [datalink: `3.3 - Rate: Fluids`]
  - 1.4 - Default: Buildings [datalink: `3.4 - Rate: Buildings`]
  - 1.5 - Default: Pollution [no data]
  - 1.6 - Default: Kills [no datalinks]
  - 1.7 - Default: Logistics [datalink `3.2.1 - Rate: Storage`]

### `Rate` - Various interpretation of "rate"
  - 3.1 - Rate: Electricity [datalink: `1.1 - Default: Electricity`]
  - 3.2 - Rate: Items [datalink: `4.1 - Misc: Items`]
  - 3.2.1 - Rate: Storage [datalink: `4.4.1 - Misc: Logistic Items`]
  - 3.2.2 - Rate: Science Packs [no datalinks]
  - 3.3 - Rate: Fluids [datalink: `1.3 - Default: Fluids`]
  - 3.4 - Rate: Buildings [datalink: `4.2 - Misc: Buildings`]
  - 3.5 - Rate: Train [WIP - no useful graphs]
  
### `Misc` - detailed presentation in various forms
  - 4.1 - Misc: Items [datalink: `3.2.1 - Rate: Storage`, `3.2 - Rate: Items`]
  - 4.2 - Misc: Buildings [datalink: `3.4 - Rate: Buildings`]
  - 4.3 - Misc: Kills [no datalink]
  - 4.4 - Misc: Logistic Network [datalink: `_internal_`, `4.4.2 - Misc: Robots`]
  - 4.4.1 - Misc: Logistic Items [datalink: `_internal_`, `3.2.1 - Rate: Storage`]
  - 4.4.2 - Misc: Robots [datalink: `_internal_`]
  - 4.5 - Misc: Train [WIP - no useful graphs]
  
All dashboards support a variety of different filters.
For example: `Force`, `TimeScale`, `Network`, `Item / Fluid / Building / etc.`
Force: default `player` - some mods provide their own identifyer.
TimeScale: default `minutes` - is used to calculate values per `seconds / minutes / hours`.
Network: default `all` - depending on context the available networks like `electricity / logistic`.
Item: default `all` -  depending on context the available entities.

`[no data]` is related to another `graftorio` fork which once included such values.
sadly @remijouannet closed my feature request to add them to this version [#18] and I'm unable to do so.
I don't script a lot in my free time and I'm not going to learn a new language - just "for a mod".

I will try to figure out how I can create an PR with those templates.
Maybe they can be the default dashboard loadout after creating the container.
Eventually they need to be imported one by one (or via script)

**Comment by Kariton** [comment]
I just realized that there is no `2.X Dashboard` 😄

**Comment by remijouannet** [comment]
hello, if you have any dashboard you feel could be part of this repo don't hesitate to open a PR or link them here so i can push them myself

**Comment by Kariton** [comment]
@remijouannet here you go: https://github.com/Kariton/graftorio2/tree/default-dashboards

what do you think?
yes, I moved data to a dedicated directory.
Users need to move their data manually, and maybe correct the permissions accordingly - if they want to keep there prometheus metrics.
I think this step is necessary to make it easy for others to maintain / update those dashboards if needed.

I would like to maintain them further.  For example make something useful out of the train data.

**Comment by Kariton** [comment]
I was actually able to add those missing metrics myself.
now the mods exports [metrics for research_queue, pollution, evolution](https://github.com/remijouannet/graftorio2/commit/b192a82aeecdc019699f640328aa461b84316920)

**Comment by Andrew-Wichmann** [comment]
These dashboards are incredible! Thank you so much @Kariton

**Comment by ben-thul** [comment]
@Kariton - are you planning on submitting a PR so that these changes can be merged upstream?

**Comment by Kariton** [comment]
Hey, @ben-thul,

Yes, I plan to create a PR to get them merged upstream.
This may happen after Christmas or in January.

In the mean time I which you all a very merry Christmas and a happy new year!

**Comment by Andrew-Wichmann** [comment]
Merry Christmas!

**Comment by Kariton** [comment]
Are you actively using my dashboards ATM?

I just pushed some new dashboards and added `${__url_time_range}` to the datalinks.
now a previously selected time range persists over datalinks.

I appreciate any suggestions for dashboards or improvements.
Still working on them before I will create an PR in the near future.

**Comment by ben-thul** [comment]
I hadn't, but just tried. I cloned your fork (had to do `git config core.protectNTFS false` due to colon characters in file names) and ran with `docker-compose up` (like I would for the mainline mod). It looks like things started okay but I'm not seeing data in any of the dashboards. I'm probably doing something wrong.

**Comment by Kariton** [comment]
Hey @ben-thul,
that's really unfortunate.

have you used this mod / setup beforehand?
did you ``git checkout default-dashboards`` to switch to the branch?

are you familiar with the ``Debugging`` description in README?
- does the ``game.prom`` exist? sounds like windows -> ``${APPDATA}\Factorio\script-output\graftorio2``
- does your compose ``prom/node-exporter volumes:`` point to the correct **folder**?
- do the container work in general?
  - can you check ``localhost:9090/targets`` you should three targets  (from ``config/prometheus/prometheus.yml``)
  
Sounds like grafana is reachable and all dashboards are loaded (even without data).
which implies that you have switched the branch.

we may figure it out if you can give some more information.
hope that helps. :)

P.S.:
the "upstream" mod is missing some metrics. due to this expect _some_ dashboards to be empty.
the fork is patched with [metrics for research_queue, pollution, evolution](https://github.com/remijouannet/graftorio2/commit/b192a82aeecdc019699f640328aa461b84316920)

a possible solution (for now) is to ZIP the cloned fork and move it in-place as graftorio2 mod.
please do your self a favor and use an "data less" structure - with nothing in ``data/{grafana,prometheus}/``
this is only needed once.
be aware that this is technically a version downgrade and the mod manage may wants to update.

**Comment by remijouannet** [comment]
i'm closing the issue since @Kariton merged a lot of great dashboards in https://github.com/remijouannet/graftorio2/pull/26
